String AUTH_CONST_SNACKBAR_MSG_LOGOUT_SUCCESS = "Logout Successful";

String AUTH_CONST_NO_ACCOUNT = "Do not have an account";
String AUTH_CONST_ALREADY_HAVE_ACCOUNT = "Already have an account";
String AUTH_CONST_LOGIN_PAGE_HEADING = "Sign In";
String AUTH_CONST_LOGIN_PAGE_DESCRIPTION = "Login to your account now";
String AUTH_CONST_FORGOT_PASSWORD_TEXT = "Forgot Password?";
String AUTH_CONST_LOGIN_PAGE_SUBMIT_BUTTON = "SIGN IN";
String AUTH_CONST_SIGNUP_PAGE_SUBMIT_BUTTON = "CREATE";
String AUTH_CONST_SIGNUP_PAGE_HEADING = "Sign Up";
String AUTH_CONST_SIGNUP_PAGE_DESCRIPTION = "Lets create a new account";
String AUTH_CONST_FORGOT_PASSWORD_PAGE_HEADING = "Forgot Password";
String AUTH_CONST_FORGOT_PASSWORD_PAGE_SUBMIT_BUTTON = "RETRIEVE PASSWORD";
String AUTH_CONST_FORGOT_PASSWORD_PAGE_DESCRIPTION = "Enter your email to get the password reset link";
