String NAVIGATION_DRAWER_CONSTS_TOP_VIEW_TEXT_SIGN_IN = "Sign In";
String NAVIGATION_DRAWER_CONSTS_TOP_VIEW_TEXT_VIEW_ACCOUNT = "View your account";

// links texts
String NAVIGATION_DRAWER_CONSTS_LINK_TEXT_HOME = "Home";
String NAVIGATION_DRAWER_CONSTS_LINK_TEXT_ALL_TESTS = "All Tests";
String NAVIGATION_DRAWER_CONSTS_LINK_TEXT_COMPLETED_TESTS = "Completed Tests";
String NAVIGATION_DRAWER_CONSTS_LINK_TEXT_GET_PREMIMUM = "Get Premium";
String NAVIGATION_DRAWER_CONSTS_LINK_TEXT_LOGOUT = "Logout";