const String TEST_DETAILS_SCREEN_CONSTS_SUBMIT_BUTTON = "START TEST";
const String TEST_DETAILS_SCREEN_CONSTS_TEXT_START_OVER = "START OVER";
const String TEST_DETAILS_SCREEN_CONSTS_OTHER_TESTS = "Explore other tests";
const String TEST_DETAILS_SCREEN_CONSTS_VIEW_TEST_SUMMARY = "Explore other tests";

const String TEST_DETAILS_SCREEN_CONSTS_SUBMIT_BTN_TEXT_START_OVER = "START OVER";
const String TEST_DETAILS_SCREEN_CONSTS_SUBMIT_BTN_TEXT = "START TEST";
const String TEST_DETAILS_SCREEN_CONSTS_SUBMIT_BTN_TEXT_CONTINUE_TEST = "CONTINUE TEST";