const String USER_PROFILE_CONST_APPBAR_TITLE = "Your Profile";
const String USER_PROFILE_CONST_SELECTED_IMAGE_APPBAR_TITLE = "Confirm Image To Upload";

const String USER_PROFILE_CONST_EDIT_PROFILE_TEXT = "Edit Profile";
const String USER_PROFILE_CONST_RESET_PASSWORD_TEXT = "Reset Password";
const String USER_PROFILE_CONST_SAVE_DETAILS_TEXT = "Save Details";

const String USER_PROFILE_CONST_PROFILE_ITEM_TEXT_NAME = "NAME";
const String USER_PROFILE_CONST_PROFILE_ITEM_TEXT_EMAIL = "EMAIL";
const String USER_PROFILE_CONST_PROFILE_ITEM_TEXT_PHONE = "PHONE";
const String USER_PROFILE_CONST_PROFILE_ITEM_TEXT_PASSWORD = "PASSWORD";

const String USER_PROFILE_EDIT_PASSWORD_PAGE_CONST_APPBAR_TITLE = "Reset Password";
const String USER_PROFILE_EDIT_PROFILE_PAGE_CONST_APPBAR_TITLE = "Edit Profile";

const String USER_PROFILE_CONSTS_UPLOAD_IMAGE_BUTTON_TEXT = "Update Profile Image";
const String USER_PROFILE_CONSTS_UPLOAD_IMAGE_CANCEL_UPLOADING = "Cancel";

const String USER_PROFILE_CONSTS_UPLOAD_IMAGE_SUCCESSFULLY = "Image uploaded successfully";